project:
  type: website 
  output-dir: docs
website:
  title: "My Quarto Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dashboard"
        href: dashboard.qmd
      - text: "Essay on Shiny Apps"
        href: ShinyApps.qmd
      - text: "Essay on Shiny Live"
        href: ShinyLive.qmd


